### ISSUE TITLE
Unable to login.  Attempting to login using interactive mode.

### ISSUE THREAD

**Issue by snugglesftw** [daryllabar/DLaB.Xrm.XrmToolBoxTools#127]
For some reason why i run this tool under xrmtoolbox, it's always falling back to interactive mode. 
Is this a bug?

xrmtoolbox- 2017-7-18
yourtool-2017-8-7
crm is ifd 2017 (8.2)

**Comment by daryllabar** [comment]
It's probably a bug mostly because I don't have examples of all of the possible connection strings required by CrmSrvUtil.  It attempts to login with whatever I'm generating, and if that fails, it falls back to interactive mode.

If you would be willing to give me some test credentials, I'd be happy to attempt to login and see if I can fix whatever the bug is.

Or

It does spit out the command line that it executes.  You could attempt to figure out what the correct command line is that works without falling back to interactive mode.

**Comment by snugglesftw** [comment]
CRM Authentication Type Detected: Federation
Executing "C:\Users\JUNNYLEE\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://ORGNAME.DOMAIN.com/XRMServices/2011/Organization.svc" /generateActions /out:"C:\alianz\Xypex\Source\Business\Alianz.Crm.Business\Actions.cs" /namespace:"Alianz.Crm.Business.Entities" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"DOMAIN\USERNAME" /password:"PASSWORD" 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
c 2015 Microsoft Corporation. All rights reserved

**Comment by daryllabar** [comment]
Try the 2017.11.13 version.  I may have fixed this...

**Comment by mjfpalmer** [comment]
Looks like this issue is back for Office365 connections. Worked fine yesterday, but not today.

I'm also suddenly having issues with connections in my own code on any connection using Office365 auth type using Microsoft.Xrm.Tooling.Connector.CrmServiceClient. I'm not sure if MS have done something that has broken this and if the two are related.

**Comment by daryllabar** [comment]
Have you tried manually downloading the latest dlls from nuget, and running the command line generated by the EBG against them?

**Comment by dkraevoy** [comment]
I am having the same problem but only with Dynamics 365 v9. Looks like starting from yesterday MSFT enforced TLS 1.2 on v9.

**Comment by daryllabar** [comment]
@dkraevoy is it as simple as upgrading to the latest version of CrmSvcUtil?

**Comment by daryllabar** [comment]
Thanks for testing.  I will have to update everything at some point in the near future then.

**Comment by mjfpalmer** [comment]
Thanks for the quick response guys. Seems you're 100% correct @dkraevoy. You've actually saved my bacon on my other code that was suddenly not able to connect.

**Comment by mjfpalmer** [comment]
Any idea when you'll release an update @daryllabar? Right now, we can't generate wrappers using your extensions. If it'll be soon, we'll hang back. If not, we'll manually recompile your extensions for .Net 4.6.2.

**Comment by daryllabar** [comment]
I'll get to it today.  Honestly though, I don't think you should have to recompile anything.  The CrmSvcUtil has to be compiled for 4.6.2, since it's the exe.   It should be able to reference dlls compiled to an older version of CRM just fine.  Just update the CrmSvcUtil, and it should just work with the older dlls.

**Comment by daryllabar** [comment]
New version published...  Verified that it is working in against a 9.0

**Comment by mjfpalmer** [comment]
Thanks @daryllabar!

**Comment by daryllabar** [comment]
Np
