### ISSUE TITLE
Does not Generate code for Multi-Select Optionset attributes

### ISSUE THREAD

**Issue by GevinVW** [daryllabar/DLaB.Xrm.XrmToolBoxTools#136]
Does not Generate code for Multi-Select Optionset attributes

**Comment by daryllabar** [comment]
I haven't even tried this yet...  Will have to figure out what it does by default and what it should do...

**Comment by GevinVW** [comment]
Thanks. I’m looking forward to this feature

**Comment by mjfpalmer** [comment]
Hi @daryllabar, any word on when you'll add support for multi-select option sets?

I think the reason that they are not being generated is that the AttributeMetadata.AttributeType is reported as Microsoft.Xrm.Sdk.Metadata.AttributeTypeCode.Virtual with a child type of MultiSelectPicklistAttributeMetadata, which is not currently handled by your extensions.

Only asking because we're having to manually add properties and constants for multi-select option sets after generating entity wrappers - which is obviously not ideal.

**Comment by mjfpalmer** [comment]
Ah wait, I see that properties are actually generated, though with a return type of object rather than OptionSetValueCollection. Any reason for that?

Field constants are still not generated though.

**Comment by daryllabar** [comment]
Sorry, life is busy.  Have you tried running the CrmSvcUtil without any of my extensions to see what gets generated?  The newest version is at least using the newest version of the CrmSvcUtil...

**Comment by mjfpalmer** [comment]
Don't worry, totally understand about life.

Haven't tried running CrmSvcUtil without the extensions as our code is built assuming your extensions have been used. I think extension-less CrmSvcUtil doesn't even generate field constants at all, or have they added that feature since I last checked (I had my own CrmSvcUtil extension to add constants before you added Early Bound Generator to the XrmToolbox)?

Will work around this for now. It just means having to hard-code multi-select option set field names and having to cast the property to an OptionSetValueCollection - both acceptable as long as we remember to come back and fix this when you get around to adding support for multi-selects.

**Comment by daryllabar** [comment]
I'm guessing you have 10 or 15 max multi-select option sets? For now I would create a separate partial class for each entity, and hard code the multi-select option sets.  As needed, with a slightly different property name (maybe post fix Enums?).  Then you'd be a able to regenerate, and not have to worry about the multi-select option sets getting lost.

Feel free to make a pull request as well.  You shouldn't have to mess with the XrmToolBox plugin itself, just the extensions.

**Comment by mjfpalmer** [comment]
Only 2 right now actually, and already in partial classes :)

Will see if I can get to modifying the extension before you do. Life is pretty busy here too...

**Comment by daryllabar** [comment]
Would you be willing to test this build? https://drive.google.com/file/d/1iO3ZkyCdAxB-9FJhVQbpdHrmpLuuKU_a/view?usp=sharing

**Comment by daryllabar** [comment]
If you select to generate enum attributes, you should get an IEnumberable<T> property,  The Object type will now be an OptionSetValueCollection.

**Comment by BenOravetz** [comment]
I just tested your build and here are the results:
- The generated entity file does not contain the System.Linq namespace in its usings declarations.  This causes a complier error with the EntityOptionSetEnum class where the Select extension is called.
- The multi-select properties are set as OptionSetValueCollection types properly but the get section still uses "this.GetAttributeValue" with object as the generic type which causes complier errors.
- The multi-select Enum classes were not generated.  As such, the Enum properties for the multi-select option set properties error out because of the missing declarations.  This could be because the multi-select option sets are not global option sets in this particular case.

**Comment by daryllabar** [comment]
@BenOravetz 
First off, thanks so much for testing!  I appreciate it!  I updated the zip file on Google drive.  Care to give it another test drive?

**Comment by BenOravetz** [comment]
@daryllabar So I ran a test and it works for the most part except for one issue.  When creating the Enum properties, it uses System.Collection.IEnumerable instead of System.Collection.Generic.IEnumerable<>, so it fails to compile.

I fixed it manually and ran my application to test, though, and everything worked as expected.

**Comment by mjfpalmer** [comment]
Sorry @daryllabar , only seeing your messages now. Looks like you're about done?

Thanks for adding this!

**Comment by daryllabar** [comment]
I just pushed out the new bits to nuget!  If there are any new bugs, let me know!  It may take a while for nuget to validate and then for the XTB store to refresh

**Comment by daryllabar** [comment]
@BenOravetz do you have a twitter or Linked in handle I can tag you with?
