### ISSUE TITLE
Text to Global Option Set Mapping Documentation / Instructions 

### ISSUE THREAD

**Issue by ryanperrymba** [daryllabar/DLaB.Xrm.XrmToolBoxTools#153]
Hi Daryl,  Just loaded up the Attribute Manager (AM).  My team is attempting to Convert a text field for state/provinces to a global option set. Given the number of views and charts, AM looks very promising!   We've noted AM requires user to first create the target global option set.  Done.  We noted it doesn't automatically create options based on source values. Created them.  We still can't get AM to copy the values from the source text field to the destination global option set.  The newest version of AM has a field to upload a mapping file. This isn't in the videos you have on youtube and I don't see any readme or documetation about the format.  Can you provide any input / documentation / guidance on how to map a text field to a global option set?

**Comment by daryllabar** [comment]
The Automatic formatting is just attempting to cast that value to the new value, since your current values are text values, it won't be able to cast them to the integer values of the global option set ("IN" and "OH" aren't numbers).  The documentation on the mapping file is sorely lacking (sometimes I add things for my own benefit and then go back and document them later for everyone else).  The mapping file is pretty simple, it will be a comma delimited file with the current value, comma, then the new value.

So in your case:

```
Alabama, 1
AL, 1
Alaska, 2
AK, 2
```

but replace the 1 and 2 with whatever your optionset value swill be going forward.  Make sense?

**Comment by daryllabar** [comment]
Feel free to re-open this if you're still having issues.

**Comment by ryanperrymba** [comment]
Daryl, you are a tribute to humanity!  We'll give this a run.  Case
sensitive or no?  We'll find out one way or another.

Ryan C. Perry
801-870-5744

**Comment by ryanperrymba** [comment]
Confirmed that is a yes.  Case sensitive. Meaning the dictionary has to
have each permutation (UT,Ut,uT,ut) to ensure it picks up any varients our
non-case sensitive validation has allowed in the state field.  It works!

Ryan C. Perry
801-870-5744
