### ISSUE TITLE
In the Beginning, Before There Was a Global OptionSet

### ISSUE THREAD

**Issue by ArtKarp** [daryllabar/DLaB.Xrm.XrmToolBoxTools#160]
Before CRM had the Global OptionSet (GOS) feature you had to duplicate the same OptionSet across multiple entities.   So if you needed the same choices across three entities you created three OptionSets, all the with same lists and IDs (hopefully).  For example, if you needed the two character country code (e.g. US, UK) you would have to duplicate the same OptionSet for all three entities.  Then, along comes the Global OptionSet feature.  So you create "Country Codes" list one more time as a GOS and use it in newly created entities as needed.   A bit of a mess that is a lot of work/development time to clean up.

It really would be great if the new Attribute tool would have the ability to select the matching (e.g. Country Code) OptionSets across multiple entities and create, or map them to, a GOS.   In my example above, you would pick the three entities that each have a single CountryCode OptionSet and select (or create) the GOS to map them to.   When you are done all three entity OptionSets would now be using only one GOS. The IDs would have been preserved/added to the GOS so nothing would break.   This would help cleanup data from CRM 2011 and earlier.  

This would only work if the new solution files, would correctly update other orgs where the fields had been previously created.   For example, when the change is made in Dev and a managed solution file is then installed into Test and Production. 

Just a thought
-Art

**Comment by daryllabar** [comment]
This is supported exactly as you describe, but it is a very manual process currently.  Here is how I would perform the change as requested:

*Note* after writing these steps a realized that you can't delete a managed attribute in the manner described.  You'll need to use the concept of a holding solution to perform this trick, as specified here http://gonzaloruizcrm.blogspot.com/2012/05/crm-2011-deleting-attributes-entities.html.  Rather than cluttering up the steps with the details of the holding solution, I've left it as is to simplify the intent of what will be required for the solutions.  Hope it helps!

1. Create the GOS.
2. Select the LOS for entity A, and check the change attribute type, selecting GOS and the GOS created in step 1.
3. In the Steps list box, uncheck anything after the Migrate to Temporary Attribute, and run the tool.  This will create a new GOS attribute for Entity A, and migrate all of the data, and customizations associated to it (forms, workflows, etc.)
4. Repeat steps 2 & 3 for entities B & C.
5. Add all temporary attributes to a new solution (Named "MigrateToTempGOS" *note* obliviously you can name the solutions whatever you'd like.  I'll just refer to them with my names) along with all of the dependencies for the temporary attributes, and export it as managed.
6. Run the step in the tool to delete the original attribute ( this should be able to be done in the CRM admin screen as well, since all dependencies should have been removed)
7. Create a new solution with Entities A, B, & C, called "DeleteLOS", and export it as managed.
8. Run the tool again for all entities, except selecting to execute all remaining steps except Delete Temporary Attribute.
9. Create the same solution as in step 5, but for the new GOS attributes. Name it MigrateToGOS and export it as managed.
10.  Run the tool to delete the temporary attributes just as in step 6, but for the final check box in the Steps list box.
11. Create a solution just like in step 7, but for the temporary GOS attributes.  Call it DeleteTempGOS, and export it as managed.
12.  Now with the managed solutions all staged, you have the required solutions to migrate each environment.
13.  In each environment, install the solutions in the order in which you exported them, except before installing the "Delete" solutions, run the tool to perform the data migration from the appropriate attribute to the appropriate attribute.

**Comment by daryllabar** [comment]
@ArtKarp Did this help?

**Comment by ArtKarp** [comment]
Hi Daryl,

Thanks for the great response.  I haven't had time to test it yet internally.  

One concern I have is being able to create a defined repeatable process that can be followed by customers within their dev/test/prod environments.  

In your process are you able to map a LOS ID to a GOS ID that are not the same?  For example, before CRM had the concept of "Publisher ID" it was just a LOS ID starting with "1" (e.g. "1", "2", "3").  Now a Publisher ID is followed by a four digit number (e.g. "912450055").   So the LOS ID could be "1" and needs to map to "912450055".  Is that possible in the steps above?

I will let you know what I learn. 

Thanks for the follow up. 
-Art

**Comment by daryllabar** [comment]
The process is a painful one when dealing with Managed solutions.  As far as the mapping goes, check this out #153
