### ISSUE TITLE
Early Bound Generator Future Plans

### ISSUE THREAD

**Issue by ashwinravi** [daryllabar/DLaB.Xrm.XrmToolBoxTools#164]
Hi @daryllabar,

Could you please let me know if this tool can support early bound generation by leveraging EDMX files instead of connecting to Dynamics, provided the EDMs are generated from Dynamics? Also, are there plans to expand this tool so that it becomes the code generation framework not only for C# code but also for TypeScript or possibly even Java?

Thanks
Ashwin

**Comment by daryllabar** [comment]
The EBG is made up of a couple of components.

1. A front end UI written in WinForms, hosted in the XrmToolBox
2. The CrmSvcUtil from Microsoft CRM SDK.
3. Custom library for extending the CrmSvcUtil.

Since I have a dependency on the CrmSvcUtil to connect to CRM, grab the metadata, and utilize the extension libraries, I'm unable to generate code for other languages, or utilize other metadata.  I do allow for reading the metadata from disk, but I would assume the xml looks nothing like an edmx file.  

So, will this ever generate TS or Java?  No.  If you're looking for TS, you may want to check out https://github.com/delegateas/XrmDefinitelyTyped
