### ISSUE TITLE
Excluded Entities List is Backwards

### ISSUE THREAD

**Issue by jblaeske** [daryllabar/DLaB.Xrm.XrmToolBoxTools#172]
Why are newly added D365 Entities automatically added to the included, rather than the excluded list?  This only makes sense under the scenario where a project is tiny.  In that scenario however there is little reason to use a filtered list of entities at all.  For a large project there is no logical reason to assume I need to automatically add newly configured Entity definitions.  In fact, going through the entire list every time I need to do an update, in order to determine if an unwanted Entity has been inadvertently added to my definitions is INCRDEADIBLY ANNOYING.  This should be an extremely simple code change.  I do not suffer this kind of lazy development well (as you can tell).

**Comment by kowgli** [comment]
Although I don't really share you irritation and don't think it's good manners to offend the author of this great extension I fully agree with what you're saying.

For me the whole include/exclude list is backward. There should be at least an option to exclude everything by default. Without the need to click through everything and store a 10.000 character long exclude list in the config file.

When generating the context I try to keep it as small as possible. Avoiding the 3MB large monster cs file. I only include the entities I'm using. 

What I would prefer is what we have with the CrmSvcUtil. If you turn on filtering (off by default), you need to specify which entities you want to keep. Not those you want to skip. Seems far more logical to me.

Because of the above I'm not using the feature of generating option set enums at all, although it would be lovely. I only want those I need. Clicking through a list of 100+ entities and excluding everything is not something I want to do. 

Might look at a fork / pull request for this. For me it would make the tool much more usable.

+ maybe a better way to store per project setting and it would be perfect.

**Comment by daryllabar** [comment]
First off, sorry for not responding.   Busy time for me.  

Secondly @jblaeske's comments not offending.  It's a logical complaint.

When I first created this back in 2012, there weren't a whole lot of OOB entities to worry about.  Now the world has changed ;)  I'll have to think about reversing the roles and have an include, rather than an exclude.

@kowgli Currently, all of the settings are stored in a config file that you can place where you'd like.  My best practice is to place the config file in the same folder as where the code will be generated.  The path is relative to the path of the config, so you can maintain different settings.

**Comment by polshgiant** [comment]
I'm trying to use the whitelist feature.  I have 3 entities whitelisted and nothing specified in the entities blacklist.  The extension is generating for all entities, seems like the whitelisting isn't working.  Is there perhaps another setting I have to set to turn it on?  (Both the extension and the settings file are 1.2019.3.19)
