### ISSUE TITLE
Personal Charts and Views aren't handled when editing attributes

### ISSUE THREAD

**Issue by daryllabar** [daryllabar/DLaB.Xrm.XrmToolBoxTools#182]
These are SavedQueryVisualization and SavedQuery records.  See #181 for a stack trace.

**Comment by daryllabar** [comment]
I believe Ryan, that the query to get the user views and charts runs as the context of the particular user, and only returns the views and charts for that particular user, so the code would have to be updated to run impersonated for every user that has a personal view/chart.

**Comment by ryanperrymba** [comment]
Interesting... I'm running XrmToolbox in my name, and looking at the list, 63 of these views were created by me, don't appear to be personal views.  What does it take to add the publish step for the views in the section noted above?

**Comment by daryllabar** [comment]
Like a publish all customizations?

**Comment by ryanperrymba** [comment]
That was my initial thought. Though, I now have more specifics for you.   

The code publishes the entity of the fromAtt before calling AssertCanDelete. It doesn't appear to publish the Views, however. Wouldn't the unpublished changes cause the AssertCanDelete to return an error?  I tested on a test entity in our sandbox. 

If dependent views are only system views on the fromAtt entty. Everything works.
If dependent views are personal views on the fromAtt entity. Everythinig works. 
**_If dependent view is a system view, on another entity "testentity2", the error in question is generated._**

So, it appears the issue is not that it is a personal view, it is that it is a view on another entity, and the changes for that entity haven't been published. I've tried manually publishing and rerunning the Migrate to Temporary attribute step, which doesn't work. So, I looked at the view on the testentity2. It doesn't appear to have been updated, so it probably isn't just that is hasn't been published.  Looking at the code / tracelog, this appears to be the case. 

The Code / Tracelog include the SQL query to identify views to be updated, and it appears likely they find only views directly on the fromAtt entity. 
```
Retrieving Views with Query: SELECT savedquery.savedqueryid, savedquery.name, savedquery.querytype, savedquery.fetchxml, savedquery.layoutxml
FROM savedquery
WHERE
( ( ( fetchxml Like '%<entity name="new_testentity">%name="new_testlocaloptionsettoglobalconversion"%</entity>%' ) 
 Or ( fetchxml Like '%<entity name="new_testentity">%attribute="new_testlocaloptionsettoglobalconversion"%</entity>%' ) 
) 
) 
```

So, unless I'm mistaken, my consclusion is that the issue isn't that it is a personal view, but that the view is on another entity.  I believe updating the SELECT statement to include these other views, and publishing changes on the related entities should fix it.  The same likely goes for any charts on other entities.

**Comment by daryllabar** [comment]
Ahh... so your saying that this is a view, in which it is not the main entity, but is a child entity and it is being referenced from there on the other entity's view/grid?

**Comment by ryanperrymba** [comment]
Yes. Other entitys' views that reference the main entity aren't updated.  I'll use this as a learning example for me to complile and load into XRM Toolbox, but am not quite up to speed on submitting a push request via github if the changes work.

**Comment by daryllabar** [comment]
The trick is to make sure you fork it first, then edit your fork...

**Comment by ryanperrymba** [comment]
Hi Daryl,

Learning curve update: Managed to clone repository to my machine, and build.  The basic documentation at https://www.xrmtoolbox.com/documentation/for-developers/debug/ works for a single plugin using the Template available directly in VS. 

This solution, with multiple projects has proven trickier.  It shows a list of missing .cs files upon loading the solution, (which I believe are later downloaded from NuGet?). Between the earlybound generator and the attribute generator, the build operations include quite a few delete and copy lines affecting DLL locations and dependencies.  After several hours between 3 of us (The other two being developers), we managed to build the solution, and the load XrmToolbox via the debugger, but not both together / with XRMTooblox finding the needed DLL for the Attribute Editor. 

Any pointers / required changes for the default github repository solution to load the debugger, as cloned before making any changes to the actual code?

**Comment by daryllabar** [comment]
You sir, deserve a 🏅.  Unfortunately, this project was created before the excellent documentation for the XTB was available.  I actually don't run the build in order to debug it.  I do the old school approach, and build the dll, put it in the bin directory of my normal XTB, run that, and then attach visual studio to the XTB process.  ( Think it's under the debug menu, attach to process). I might be able to do a screen share with you if you're still having problems.

The other .cs files in the App_Packages folder are supposed to be installed by NuGet.  You can try direct messaging me in Twitter or LinkedIn for a quicker response time.

**Comment by ryanperrymba** [comment]
Thanks for taking the Pull request on #184. I somewhat expected to see a summary showing changes accepted on lines by line basis, with several not accepted, as there were a number of comments not necessary in the main branch, but still included in the commit as we hadn't discussed. (IE, variants of the query I tried while testing before getting it to work).  All good? Just want to keep things clean.  If so, I think this thread is probably also good to close.

**Comment by daryllabar** [comment]
You can view the latest commit. I saw those changes, and pulled them out when I built the newest version today.  If there is anything you think I missed, let me know.

**Comment by ryanperrymba** [comment]
Found it. Thanks for bringing me up to speed somewhat on version mgt, etc.
My mind is exploding! I'm seeing tons of little things that could be done.
You indicated this can be done directly in VS, rather than via Git Bash...
I'll have to figure that out.

I noted the query counts records to be updated via FetchXML, but uses the
queryexpression class when running updates.  Is there a reason for this?
FetchXML is capped at 50K records (noted in code), though in our system I
think it is set at 100K.  While the UI only shows 5K record count, we can
export 100K to excel.  I think the way Attribute Manager processes the
updates, it will still update above 50K records, but am not clear if there
is a record limit for the queryexpression class.  I guess I'll know if it's
under 100K shortly. If not, may be running manual data migration.

LMK if there is anything I can do to help further.


Ryan C. Perry
801-870-5744
