### ISSUE TITLE
Early Bound Generator doesn't provide a list of Custom APIs to generate classes for

### ISSUE THREAD

**Issue by ghost** [daryllabar/DLaB.Xrm.XrmToolBoxTools#298]
Microsoft has introduced a replacement for custom process actions - custom APIs (https://docs.microsoft.com/en-us/powerapps/developer/data-platform/custom-api). Early Bound Generator currently doesn't offer to generate classes for such requests, would be nice if you implement this feature.

**Comment by daryllabar** [comment]
It sort of does.  The problem is that just queries the workflow table to get a list of Actions, and API's are stored separately.  For now, try manually adding the API (Without the Request/Response postfix) to your Workflowless actions settings and then selecting it in your white list.  

![image](https://user-images.githubusercontent.com/9728423/127655652-a631d6c9-8be9-4838-99f9-f4146c2121f7.png)

Looks like I can Query the CustomAPI table and add those custom APIs to the white/black list now as well.

**Comment by Mihails-Simvulidi-CGI** [comment]
Thank you, haven't noticed the Workflowless Actions setting. :)

**Comment by Mihails-Simvulidi-CGI** [comment]
It isn't convenient that when using the white list feature I have to specify custom API in both **Workflowless Actions** and in **Actions Whitelist**. I would expect that these two are combined behind the scenes.

**Comment by daryllabar** [comment]
Agreed.  I should be automatically loading the Actions and Custom APIs and presenting them both in the Whitelist.  I'm still at a lost as to why some show up that aren't in the Custom API Table.  Must be some other Table for MS APIs....

**Comment by daryllabar** [comment]
This might help https://github.com/GuidoPreite/DRB/blob/main/js/drb.common.xrm.js#L41
