### ISSUE TITLE
Docs for v2! What is `builderSettings.json`?

### ISSUE THREAD

**Issue by skfd** [daryllabar/DLaB.Xrm.XrmToolBoxTools#394]
Fantastic work with version 2!

Just wanted to ask for some docs explaining the new config file format. Should this be a dot file like `.builderSettings` and git ignored?

**Comment by daryllabar** [comment]
Good point.  Added to the doc (https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder)

6. **CrmSvcUtil.exe.config replaced by builderSettings.json** - EBG-v1 would populate the CrmSvcUtil.exe.config file in the _XTB\Plugins\EarlyBoundGenerator_ folder and then shell out to the CrmSvcUtil in order to generate the entities.  This worked but was kind of a hack since the CrmSvcUtil.exe assumed all parameters were inputted via the command line.  Microsoft instead allows for the specification of a json file that is used to define the settings to be used.  The EBG-v2 maps its settings to the MS properties in this file, as well as it's own custom properties in the "dLaB.ModelBuilder" property.  It is recommended to check this file into source control if there is a desire to generate the entities via the PAC command line.  Being JSON it may be easier to see changes in configuration of settings used to generate the classes than in the _DLaB.EarlyBoundGenerator.Settings.xml_ file, and is another valid reason to check the file into source control, but again, there is no requirement to since it will be regenerated by the EBG-v2.

**Comment by daryllabar** [comment]
Let me know if that wasn't what you're looking for.

**Comment by skfd** [comment]
That's exactly what I wanted, thank you! Trying to upgrade my project now
