### ISSUE TITLE
1.2016.4.27 - Doesn't change attribute casing

### ISSUE THREAD

**Issue by luke-oppcos** [daryllabar/DLaB.Xrm.XrmToolBoxTools#40]
When I use the "Specify Attribute Names" the names are not updated with the casing that I have specified.

- attribute name in CRM: "new_attribtecomplexname"
- generated name: "New_attribtecomplexname"
- expected name: "New_AttribteComplexName"

This appears to be a regression from the previous version.

**Comment by daryllabar** [comment]
Is this for an OptionSet Attribute?

**Comment by luke-oppcos** [comment]
I am seeing this on DateTime, Two Options, Single Line Text, Whole Number and Lookup attributes. I don't have an OptionSet attribute that I am changing the casing on but it appears to be any type of attribute.

**Comment by daryllabar** [comment]
Figured out the bug... I switched the parsing of the config value for KeyValuePairs Hopefully this weekend I can find time to fix the root cause.  For now, you can update your CrmSvcUtil.exe.config, and replace each comma after the account logical name with a Colon, and then run the command line manually as a work around...  so 

entity,attribute1,attribute2|entity,attribute1 

goes to 

entity:attribute1,attribute2|entity:attribute1

**Comment by daryllabar** [comment]
Closed with version 2016.5.25
