### ISSUE TITLE
Naming Entity File

### ISSUE THREAD

**Issue by Marvinnnne** [daryllabar/DLaB.Xrm.XrmToolBoxTools#487]
**Tool and Version**
EarlyBoundGenerator V 2.2024.2.1

**Describe the bug**
I try to generate a specific name for my entity file because my plugin have the same name and it make difficult to read code. The CamelCase is broken.
Maybe there is a parameter to add a suffix or prefix to generate files ?

See attachment
<img width="120" alt="result" src="https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9744563/46732d24-9282-412a-802d-23138305c6e7">
<img width="326" alt="settings" src="https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9744563/0dc823a5-c744-46bf-83c8-31ce21814e6c">

**Comment by daryllabar** [comment]
The issue is that when it attempts to parse the letters into works, the first word it finds is Tea, and then it tries to parse the rest, and fails miserably.    Good news is you can fix this with configuration.  If you want it cased as "Accountea" and "Appointmentea" then you just need to add "Accountea" and "Appointmentea" as custom words:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/4863a0ff-8ae4-4f69-ba5c-3f67a8af995e)
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/b8fe0106-b8f3-4ea1-aa5b-a707d84e1bab)

if you want some other casing, use the Token Capitalization Override
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/14a05ba0-ef48-4b6c-aa66-00be89c7840d)
and enter the exact casing you want, maybe "AccountEa" or "AccountEA"

**Comment by Marvinnnne** [comment]
Maybe i'm doing something wrong or I didn't understand but I put accountea and appointmentea in camel case custom word, remove namespace, and add AccountEA in token capitalization overrides but, the file name is still Account or Appointment.

What did I do wrong ?

**Comment by Marvinnnne** [comment]
I add _EA at the end of each class I need.
It seems working.
<img width="383" alt="solution" src="https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9744563/8aaacb30-9d5f-4da4-bca7-d1fe35079dc5">

**Comment by daryllabar** [comment]
Oh, are you trying to rename it to Account_EA or AccountEA?
