### ISSUE TITLE
Skipping OptionSet yesornoselectiontype. OptionSet is a global optionset, skipping entity level add.

### ISSUE THREAD

**Issue by Marvinnnne** [daryllabar/DLaB.Xrm.XrmToolBoxTools#507]
EarlyBoundGenerator V 2.2024.5.16

I use the global option set yesornoselectiontype but I can't generate it because of this error : 
Skipping OptionSet yesornoselectiontype. OptionSet is a global optionset, skipping entity level add.

This is my settings : 
![image](https://github.com/user-attachments/assets/00f9d01c-93f3-43b0-b19a-7a9e129e2c3b)

And when I put to False Generate Global Option Set, I have the Global OptionSet yesornoselectiontype but it delete all the other usefull optionset.

Not sure to understand how it's working.

Thank you for your help.

Best regards,

**Comment by daryllabar** [comment]
This isn't an error:
```
Skipping OptionSet yesornoselectiontype. OptionSet is a global optionset, skipping entity level add.
```
It just a log message from the PAC model builder that an entity uses the option set, but it isn't going to be added to the entity file, because it's a global option set, which will be generated in it's own cs file.

If "Generate Global Option Set" is true, all global optionsets will be generated.  If it is false, only the global option sets that are referenced by the entities generated, will be generated.  I should probably change the display name to "Generate Unreferenced Global Option Sets".

Does that help?

**Comment by Marvinnnne** [comment]
Okay I better understand but this global option set is not generated with Generate Global Option Sets to True, only when it's false.

**Comment by daryllabar** [comment]
Do you have an entity that utilizes it as an option set attribute?

**Comment by Marvinnnne** [comment]
Yes Quote

![image](https://github.com/user-attachments/assets/63613b8a-b027-4a4f-a012-1fb7701503d6)

**Comment by Marvinnnne** [comment]
But If I understand correctly, I should put Generate Global Option Sets to False in order to clean my repo and delete the useless Global Option Set

**Comment by daryllabar** [comment]
Yes.  Put that value to false, and then upload your [metadata and config files](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Submitting-Metadata-For-Debugging) and I'll debug it.  As long as Quote_EA is bring generated, the YesOrNoSelectionType should be getting generated in it's own file in the OptionSets folder.

**Comment by Marvinnnne** [comment]
No need, now that I put to false and delete all the useless global option set, it works. 
Thank for your clarification ! :)

Great tools, thanks for your work !
