### ISSUE TITLE
Change Field Type to Static Class

### ISSUE THREAD

**Issue by daryllabar** [daryllabar/DLaB.Xrm.XrmToolBoxTools#82]
http://stackoverflow.com/questions/2223162/c-sharp-static-class-vs-struct-for-predefined-strings

**Comment by daryllabar** [comment]
Generated Class is not Static.  Wanna give it another shot?

**Comment by derekfinlinson** [comment]
From what I've been able to find through testing and binging (better support MS right?), it's not possible to mark a class Static using CodeDom since that is just a C# feature and not part of the CLR. The recommended approach seems to be to mark it as abstract and sealed since that's what it gets compiled to in the end.

**Comment by daryllabar** [comment]
Hmm… Does this work? http://stackoverflow.com/a/8345616/227436

**Comment by daryllabar** [comment]
I pretty much removed everything you added, but thanks for the inspiration!  ;)

**Comment by derekfinlinson** [comment]
Glad I could sorta help :)
