### ISSUE TITLE
OptionSet Attributes Are Getting Generated as Objects Not OptionSetValues

### ISSUE THREAD

**Issue by micheleietri** [daryllabar/DLaB.Xrm.XrmToolBoxTools#87]
As said on titile, whith the last update (3.3) optionset values are being generated as object type instead of int as before, but the optionsets classes are generated well.

Also, there is any optionset for state code.

**Comment by MscrmTools** [comment]
My colleague has the same kind of behavior but the `OptionSetValue` attribute are also returned as `object`

**Comment by daryllabar** [comment]
So the nullable int option sets are no longer nullable ints, but objects?  Or are these the default OptionSetValue properties?

**Comment by MscrmTools** [comment]
This is what is generated for an optionset

    [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("collec_statutclientcollectifcode")]
		public object collec_StatutClientCollectifCode
		{
			get
			{
				return this.GetAttributeValue<object>("collec_statutclientcollectifcode");
			}
			set
			{
				this.OnPropertyChanging("collec_StatutClientCollectifCode");
				this.SetAttributeValue("collec_statutclientcollectifcode", value);
				this.OnPropertyChanged("collec_StatutClientCollectifCode");
			}
		}

**Comment by daryllabar** [comment]
I'm seeing this difference as well. I'll get on the horn with MS again...

![image](https://cloud.githubusercontent.com/assets/9728423/23612887/2fae6f36-024b-11e7-8765-bfb3839590d4.png)

**Comment by MscrmTools** [comment]
I don't know what they are doing with this utility but it is a lot of mess...

**Comment by skfd** [comment]
> I don't know what they are doing with this utility but it is a lot of mess...
Preparing to open source, hopefully!

**Comment by robertpiska** [comment]
I have the same issue

**Comment by ChrisH-ISC** [comment]
I am also seeing this and wondering how to set the optionset value when creating a new record?
This is how I used to do it, how do we do it now?

newAccount.AccountCategoryCode = 100003;

**Comment by daryllabar** [comment]
@ChrisH-ISC Does this not work?
    
`newAccount.AccountCategoryCode = new OptionSetValue(100003);`

**Comment by ChrisH-ISC** [comment]
(facepalm) doh!  

Sorry, didn't think if that...thanks!

**Comment by daryllabar** [comment]
Ok, some news back from MS.  There is going to be an attempt to restore the CrmSvcUtil back to using OptionSetValues, rather than objects.  If this succeeds, then I'll be able to utilize that and everything will be working again.

**Comment by daryllabar** [comment]
I have tested an internal build from MS.  Thinks looks good!  Once it's on NuGet, I'll get an update deployed.

**Comment by somefella123** [comment]
v8.2.0.4 is now available on NuGet. 

"Fixes: 
 Addressed an issue with customers who use optionset type generators and or linq class access that do not have a handler to define type enum’s for optionsets.  This update will provide support for older behaviors in addition to supporting developers who use enum based optionset generators "

**Comment by daryllabar** [comment]
@somefella123  if you download that nuget package (unblock), and then overwrite the files in the plugins\CrmSvcUtil folder (except for the .config file, keep that)  Does that work?

**Comment by daryllabar** [comment]
I've pushed a new version.  Should be in the plugin store, 

![6a0120a85dcdae970b0128776ff992970c-pi 1](https://cloud.githubusercontent.com/assets/9728423/24252048/b7c080fc-0fb2-11e7-80d0-bcd9f7a9ddfe.png)

**Comment by somefella123** [comment]
The latest version "works on my machine" too. All good!

**Comment by MBeecher** [comment]
I just wanted to check to see if I'm reading this thread correctly.

OptionSets built with CrmSvcUtil are now typed as Microsoft.Xrm.Sdk.OptionSetValue, instead of System.Nullable<int> ... is that correct? I'm working with an older project against 8.2-on-premise and porting it over to Dynamics 365 v9 online.

Is there any way to build the Entities.cs file with Nullable<int>, or is that a thing of the past now and it's OptionSetValue from here on in?

**Comment by daryllabar** [comment]
They've never generated as nullable.  There is an option to generate nullable enum properties, but it generates both the enum properties and options properties

**Comment by MBeecher** [comment]
I wonder if this is a result of being so far behind on the version of the crmsvcutil and microsoft.xrm.sdk that were used for these projects initially. This is what I'm seeing, just for reference. I built the Entities 5 different ways: 1) our archived, legacy crmsvcutil/SDK against on-premise v8.2 CRM and then with EBG and w/latest crmsvcutil/SDK from NuGet
2) on-prem 8.2 without nullable enum properties
3) on-prem 8.2 with nullable enum properties
4) online 9 without nullable enum properties
5) online 9 with nullable enum properties

What you describe detailed below for variations 2-5, but variation 1 is what the projects were all written against... Since variation 1 was built with such an outdated version of the tools, it looks like the functionality was deprecated at some point and I've got some rewriting to do<g>.

1) Build stored in TFS trunk against on-prem v. 8.2
crmsvcutil v5.0.9690.3739
microsoft.xrm.sdk v5.0.9910.15
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_constituentrole")]
		public System.Nullable<int> wsob_ConstituentRole
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("wsob_constituentrole");
			}
			set
			{
				this.SetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_ConstituentRole", "wsob_constituentrole", value);
			}
		}

2) Use XrmToolBox against on-prem v.8.2 "Generate Enum Properties" = false
crmsvcutil v9.0.0.9369
microsoft.xrm.sdk 9.0.9002

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_constituentrole")]
		public Microsoft.Xrm.Sdk.OptionSetValue wsob_ConstituentRole
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_constituentrole");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("wsob_ConstituentRole");
				this.SetAttributeValue("wsob_constituentrole", value);
				this.OnPropertyChanged("wsob_ConstituentRole");
			}
		}

3) Use XrmToolBox against on-prem v8.2 "Generate Enum Properties" = true
crmsvcutil v9.0.0.9369
microsoft.xrm.sdk 9.0.9002

		<same OptionSetValue type present as 2>

		public virtual wsob_ConstituentRole? wsob_ConstituentRoleEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((wsob_ConstituentRole?)(EntityOptionSetEnum.GetEnum(this, "wsob_constituentrole")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				wsob_ConstituentRole = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}

4) XrmToolBox against online "Generate Enum Properties" = false
crmsvcutil v9.0.0.9369
microsoft.xrm.sdk 9.0.9002

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_constituentrole")]
		public Microsoft.Xrm.Sdk.OptionSetValue wsob_ConstituentRole
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_constituentrole");
			}
			set
			{
				this.OnPropertyChanging("wsob_ConstituentRole");
				this.SetAttributeValue("wsob_constituentrole", value);
				this.OnPropertyChanged("wsob_ConstituentRole");
			}
		}
		
		
5) XrmToolBox against online "Generate Enum Properties" = true
crmsvcutil v9.0.0.9369
microsoft.xrm.sdk 9.0.9002
		<same OptionSetValue type present as 4>

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_constituentrole")]
		public virtual wsob_ConstituentRole? wsob_ConstituentRoleEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((wsob_ConstituentRole?)(EntityOptionSetEnum.GetEnum(this, "wsob_constituentrole")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				wsob_ConstituentRole = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}

**Comment by daryllabar** [comment]
@MBeecher did you get a copy paste error for #1?  I don't think that code as written will work.  It will always return a null value I think.  I have also never seen that before.  Back in the day there were a large number of custom Crmsvcutils that attempted to provide optionset enum generation.  My best guess is that one of these was used "back in the day"

**Comment by MBeecher** [comment]
Interesting, the first example didn't format like the others did. Here's another optionSet Property from that same old-school Entities.cs file:

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_programapplied")]
		public System.Nullable<int> wsob_ProgramApplied
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("wsob_programapplied");
			}
			set
			{
				this.SetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_ProgramApplied", "wsob_programapplied", value);
			}
		}

Aha! I tried EBG with "Use Xrm Client=true", since the command-line batch-file that generated the code above (example 1) used  codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization, Microsoft.Xrm.Client.CodeGeneration". This is the output from EBG with "Use Xrm Client=true":

		/// <summary>
		/// Program Applicant applied to
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_programapplied")]
		public System.Nullable<int> wsob_ProgramApplied
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("wsob_programapplied");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_ProgramApplied", "wsob_programapplied", value);
			}
		}

and

		/// <summary>
		/// Constituent Role in which activity occurred
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("wsob_constituentrole")]
		public System.Nullable<int> wsob_ConstituentRole
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("wsob_constituentrole");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("wsob_ConstituentRole", "wsob_constituentrole", value);
			}
		}

I've read that Microsoft.Xrm.Client is now problematic, since it's not included in the SDK anymore.

(And, again, my thanks for your insight into the state of the toolset!!)
